### ISSUE TITLE
can not install hezar library what is compatible python version with this library

### ISSUE THREAD

**Issue by muhammadCodeSh** [hezarai/hezar#118]
when install hezar library i got this error with **python 3.12**
```
ERROR: Could not find a version that satisfies the requirement torch<2.1.0,>=1.10.0 (from hezar) (from versions: none)      
ERROR: No matching distribution found for torch<2.1.0,>=1.10.0
```

to solve it I tried to downgrade my python version to 3.8 or 3.7 but after installation when run my code

```
from hezar import Dataset
xlsum_dataset = Dataset.load("hezarai/xlsum-fa")
```

this is log when run above code by **python 3.7**
```

PS E:\python\hezar> python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from hezar import Dataset
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\__init__.py", line 24, in __getattr__
    from .data import Dataset
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\data\__init__.py", line 1, in <module>
    from .data_collators import *
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\data\data_collators.py", line 4, in <module>      
    from ..preprocessors import Tokenizer
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\preprocessors\__init__.py", line 1, in <module>   
    from ..registry import register_preprocessor  # noqa
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\registry.py", line 30, in <module>
    from .configs import (
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\configs.py", line 26, in <module>
    from .utils import Logger, get_module_config_class
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\utils\__init__.py", line 1, in <module>
    from .audio_utils import *
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\utils\audio_utils.py", line 9, in <module>        
    from .integration_utils import is_backend_available
  File "C:\Users\ASUS\AppData\Roaming\Python\Python37\site-packages\hezar\utils\integration_utils.py", line 2, in <module>  
    from importlib.metadata import version
ModuleNotFoundError: No module named 'importlib.metadata'
```

**Comment by arxyzan** [comment]
Hello @muhammadCodeSh and thanks for opening this issue. Hezar is currently only installable with Python 3.8 up to 3.11.
