### ISSUE TITLE
Compatible hezar with python 3.12

### ISSUE THREAD

**Issue by zaaferani** [hezarai/hezar#179]
For now, hezar will installing until python 3.11.
Please compatible hezar with python 3.12

**Comment by arxyzan** [comment]
Hi @zaaferani, can you please paste the errors you get with the 3.12 build?

**Comment by zaaferani** [comment]
@arxyzan 
```
└──╼  $ pip install hezar[all]
Collecting hezar[all]
  Using cached hezar-0.41.0-py3-none-any.whl.metadata (18 kB)
Collecting accelerate>=0.27.0 (from hezar[all])
  Using cached accelerate-1.0.1-py3-none-any.whl.metadata (19 kB)
Collecting datasets>=2.9.0 (from hezar[all])
  Downloading datasets-3.0.2-py3-none-any.whl.metadata (20 kB)
Collecting gensim==4.3.2 (from hezar[all])
  Using cached gensim-4.3.2.tar.gz (23.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting huggingface_hub>=0.12.0 (from hezar[all])
  Using cached huggingface_hub-0.26.1-py3-none-any.whl.metadata (13 kB)
Collecting jiwer>=3 (from hezar[all])
  Using cached jiwer-3.0.4-py3-none-any.whl.metadata (2.6 kB)
Collecting librosa>=0.10.0 (from hezar[all])
  Using cached librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
Collecting nltk>=3.8.0 (from hezar[all])
  Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting numpy==1.24.* (from hezar[all])
  Using cached numpy-1.24.4.tar.gz (10.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**Comment by alicompu** [comment]
> @arxyzan
> 
> ```
> └──╼  $ pip install hezar[all]
> Collecting hezar[all]
>   Using cached hezar-0.41.0-py3-none-any.whl.metadata (18 kB)
> Collecting accelerate>=0.27.0 (from hezar[all])
>   Using cached accelerate-1.0.1-py3-none-any.whl.metadata (19 kB)
> Collecting datasets>=2.9.0 (from hezar[all])
>   Downloading datasets-3.0.2-py3-none-any.whl.metadata (20 kB)
> Collecting gensim==4.3.2 (from hezar[all])
>   Using cached gensim-4.3.2.tar.gz (23.3 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... done
>   Preparing metadata (pyproject.toml) ... done
> Collecting huggingface_hub>=0.12.0 (from hezar[all])
>   Using cached huggingface_hub-0.26.1-py3-none-any.whl.metadata (13 kB)
> Collecting jiwer>=3 (from hezar[all])
>   Using cached jiwer-3.0.4-py3-none-any.whl.metadata (2.6 kB)
> Collecting librosa>=0.10.0 (from hezar[all])
>   Using cached librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
> Collecting nltk>=3.8.0 (from hezar[all])
>   Using cached nltk-3.9.1-py3-none-any.whl.metadata (2.9 kB)
> Collecting numpy==1.24.* (from hezar[all])
>   Using cached numpy-1.24.4.tar.gz (10.9 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [33 lines of output]
>       Traceback (most recent call last):
>         File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
>           backend = _build_backend()
>                     ^^^^^^^^^^^^^^^^
>         File "/home/hassan/Desktop/testing/llm/hezar/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
>           obj = import_module(mod_path)
>                 ^^^^^^^^^^^^^^^^^^^^^^^
>         File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
>           return _bootstrap._gcd_import(name[level:], package, level)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "<frozen importlib._bootstrap_external>", line 995, in exec_module
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
>         File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 16, in <module>
>           import setuptools.version
>         File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/setuptools/version.py", line 1, in <module>
>           import pkg_resources
>         File "/tmp/pip-build-env-emqlpjp8/overlay/lib/python3.12/site-packages/pkg_resources/__init__.py", line 2172, in <module>
>           register_finder(pkgutil.ImpImporter, find_on_path)
>                           ^^^^^^^^^^^^^^^^^^^
>       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ```

Hi bro, I have this problem
Did you fix this problem?

**Comment by alicompu** [comment]
> Hi @zaaferani , the problem lies within the numpy side. When you install the `hezar[all]` package, it installs numpy==1.24.* so that the embedding models work (due to a bug in Gensim), and numpy==1.24.* has no wheels for python 3.12 yet (maybe never!). I'm trying to work on a solution so that hezar works without that dependency.

Okay bro 
thank you,
Is this repository working correctly with the specified Python version?

**Comment by alicompu** [comment]
I want to use all features

**Comment by arxyzan** [comment]
@zaaferani Yes it does, you just have to make sure your python version is below 3.12 for now.

**Comment by alicompu** [comment]
> @zaaferani Yes it does, you just have to make sure your python version is below 3.12 for now.

Thanks for all answers.
